In [13]:
import numpy as np
import matplotlib.pyplot as plt
import cv2 as cv

#image=cv.imread('sam.jpg',0)
image=np.array([
    [1,3,4,9],
    [7,2,1,0],
    [6,6,9,0]
])
row , col =image.shape
# ---------------------------------- define function difference X ----------------------------------
def f_dif_x(img):    
    r , c =img.shape
    d_x=img.copy()
    for i in range(r-1):
        for j in range(c):
            d_x[i,j]=img[i+1,j]-img[i,j]
    return d_x

# ---------------------------------- define function difference Y ----------------------------------
def f_dif_y(img):
    d_y=img.copy()
    r ,c =img.shape
    for i in range(r):
        for j in range(c-1):
            d_y[i,j]=img[i,j+1]-img[i,j]
    return d_y


diff_x=f_dif_x(image)
diff2_x=f_dif_x(diff_x)
diff_y=f_dif_y(image)
diff2_y=f_dif_y(diff_y)
print('x is row and y is col')
print()
print('original image :')
print(image)
print()
print('difference x: ')
print(diff_x)
print()
print('difference 2 x : ')
print(diff2_x)
print()
print('difference y: ')
print(diff_y)
print()
print('difference 2 y: ')
print(diff2_y)

x is row and y is col

original image :
[[1 3 4 9]
 [7 2 1 0]
 [6 6 9 0]]

difference x: 
[[ 6 -1 -3 -9]
 [-1  4  8  0]
 [ 6  6  9  0]]

difference 2 x : 
[[-7  5 11  9]
 [ 7  2  1  0]
 [ 6  6  9  0]]

difference y: 
[[ 2  1  5  9]
 [-5 -1 -1  0]
 [ 0  3 -9  0]]

difference 2 y: 
[[ -1   4   4   9]
 [  4   0   1   0]
 [  3 -12   9   0]]
